### ISSUE TITLE
EXAMPLE_PATCH_PATH is required, but says optional in the documentation

### ISSUE THREAD

**Issue by f1sherman** [test-prof/test-prof-aiptimize-action#2]
Thanks for this great GitHub action! I just wanted to report a minor bug.

In the README, it says that EXAMPLE_PATCH_PATH is optional, but it errors if not provided:

```
main.rb:67:in `fetch': key not found: "EXAMPLE_PATCH_PATH" (KeyError)
        from main.rb:67:in `<main>'
```

**Comment by f1sherman** [comment]
My apologies, I was trying to run this from the command line to try to figure out how it works, but just realized this is all handled in the GitHub action yaml 🤦.
